-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 71, Failures: 4, Errors: 0, Skipped: 2, Time elapsed: 14.569 sec <<< FAILURE!
findErroAttendace(com.ehr.cases.ehr_attendance)  Time elapsed: 1.578 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.ehr.cases.ehr_attendance.findErroAttendace(ehr_attendance.java:107)

overtimeApply(com.ehr.cases.ehr_attendance)  Time elapsed: 0.453 sec  <<< FAILURE!
java.lang.NullPointerException
	at com.ehr.cases.ehr_attendance.overtimeApply(ehr_attendance.java:184)

OvertimeRevocation(com.ehr.cases.ehr_attendance)  Time elapsed: 0.059 sec  <<< FAILURE!
java.lang.AssertionError: expected [操作成功] but found [存在审批中或审批通过的撤销单据，不可重复撤销]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.ehr.cases.ehr_attendance.OvertimeRevocation(ehr_attendance.java:236)

taskCompleteBatch(com.ehr.cases.ehr_attendance)  Time elapsed: 0.035 sec  <<< FAILURE!
java.lang.AssertionError: expected [操作成功] but found [离职申请审批,不支持批量操作,请重新选择]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.ehr.cases.ehr_attendance.taskCompleteBatch(ehr_attendance.java:387)

