<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.ehr.cases.ehr_attendance" tests="7" time="1.551" ignored="0" failures="0" timestamp="30 Jun 2020 03:25:43 GMT" skipped="6" hostname="BF400255" errors="1">
  <testcase name="fillCheckApply" time="0.000" classname="com.ehr.cases.ehr_attendance">
    <skipped/>
  </testcase> <!-- fillCheckApply -->
  <testcase name="TaskToDo" time="0.000" classname="com.ehr.cases.ehr_attendance">
    <skipped/>
  </testcase> <!-- TaskToDo -->
  <testcase name="taskTransfer" time="0.000" classname="com.ehr.cases.ehr_attendance">
    <skipped/>
  </testcase> <!-- taskTransfer -->
  <testcase name="vacationApply" time="0.000" classname="com.ehr.cases.ehr_attendance">
    <skipped/>
  </testcase> <!-- vacationApply -->
  <testcase name="taskCompleteBatch" time="0.000" classname="com.ehr.cases.ehr_attendance">
    <skipped/>
  </testcase> <!-- taskCompleteBatch -->
  <testcase name="findErroAttendace" time="1.551" classname="com.ehr.cases.ehr_attendance">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.ehr.cases.ehr_attendance.findErroAttendace(ehr_attendance.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:74)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:93)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:145)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
]]>
    </error>
  </testcase> <!-- findErroAttendace -->
  <testcase name="getAllPageTask" time="0.000" classname="com.ehr.cases.ehr_attendance">
    <skipped/>
  </testcase> <!-- getAllPageTask -->
</testsuite> <!-- com.ehr.cases.ehr_attendance -->
